---
driver:
  name: vagrant
  provision: true
  provision_command: "echo \"gem: --no-user-install\" > /etc/gemrc"

busser:
  sudo: true
  ruby_bindir: '/usr/bin'
  busser_bin: '/home/vagrant/.gem/ruby/2.2.0/bin/busser'

provisioner:
  name: chef_zero

platforms:
  - name: arch
    driver_config:
      box: arch-chef
      disable_upstart: true
      require_chef_omnibus: false
    provisioner:
      name: chef_zero
      chef_client_path: /usr/bin/chef-client

suites:
  - name: default
    driver_config:
      hostname: default
    run_list:
      - 'recipe[docker-simple]'
      - 'recipe[docker-simple::compose]'
    data_bags_path: 'test/integration/data_bags'
    attributes:
      containers: [
        'nginx'
      ]
